name: Deploy Package

permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  # TODO: Maybe add auto-updating to internal change-log
  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: install Dependencies
        run: |
          pip3 install -r scripts/requirements.txt

      - name: Update Information Script
        env:
          INFO_PATH: src/ForbiddenAPI/Information.server.lua

          # Used to find where to place the new log
          LOG_LOC_TEXT: "<-- UPDATE -->"
        run: |
          # Generate changlog
          changlog=$(python3 scripts/release-to-info.py V.1.1.7 -r https://github.com/prooheckcp/RobloxStateMachine)
          echo -e "$changlog"

          # Add to info path
          '/<!-- UPDATE -->/a Hello World'
          sed "/$LOG_LOC_TEXT/a $changelog" $INFO_PATH

  wally:
    name: Deploy Wally
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install wally packages
        runs: |
          wally install

      - name: Deploy new version
        runs: |
          wally publish --token ${{ secrets.GITHUB_TOKEN }}

  roblox:
    name: Deploy Roblox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install wally packages
        runs: |
          wally install

      - name: Build project
        run: rojo build -o "ForbiddenAPI.rbxm"

      - name: Add build to Release
        run: |
          gh release upload ${{ github.GITHUB_REF_NAME }} "ForbiddenAPI.rbxm" --clobber

      - name: Push to Roblox
        run: |
          rbxcloud assets update -f "ForbiddenAPI.rbxm" -p ${{ vars.ASSET_ID }} -t model-fbx -a ${{ secrets.OPEN_CLOUD_TOKEN }}
