name: Deploy Package

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    outputs:
      final-tag: ${{ steps.set-final-tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Get branch
        run: |
          branch=$(git rev-parse HEAD)
          echo "BRANCH=$branch" > $GITHUB_ENV

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: install Dependencies
        run: |
          pip3 install -r scripts/requirements.txt

      - name: Update Information Script
        env:
          INFO_PATH: src/Forbidden/Information.server.lua

          # Used to find where to place the new log
          LOG_LOC_TEXT: "<!-- UPDATE -->"
        run: |
          # Generate changelog
          changelog=$(python3 scripts/release-to-info.py ${{ github.ref_name }} -r $GITHUB_REPOSITORY)
          echo -e "$changelog"

          # Add to info path
          sed -e "/$LOG_LOC_TEXT/a $changelog" -e 's/\/$//' $INFO_PATH > $INFO_PATH

          echo $INFO_PATH

      - name: Determine updated tag name
        id: set-final-tag
        run: echo "final-tag=${{ github.ref_name }}-final" ?> "$GITHUB_OUTPUT"

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update info on Release"
          git tag ${{ steps.set-final-tag.outputs.final-tag }}
          git push  --follow-tags

      - name: Fix release tag
        env:
          NEW_TAG_NAME: ${{ steps.set-final-tag.outputs.final-tag }}
        run: |
          gh release edit ${{ github.ref_name }} --tag $NEW_TAG_NAME

  wally:
    name: Deploy Wally
    runs-on: ubuntu-latest
    needs: [changelog] # NOTE: Technically not needed, but for better action graph
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.set-final-tag.outputs.final-tag }}

      - name: Install aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install wally packages
        run: |
          wally install

      - name: Deploy new version
        run: |
          wally publish --token ${{ secrets.GITHUB_TOKEN }}

  roblox:
    name: Deploy Roblox
    runs-on: ubuntu-latest
    needs: [changelog]
    env:
      NEW_TAG_NAME: ${{ needs.changelog.outputs.final-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.checkout.outputs.final-tag }}

      - name: Install aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install wally packages
        run: |
          wally install

      - name: Build project
        run: rojo build -o "Forbidden.rbxm"

      - name: Add Build to Release
        run: |
          gh release upload $NEW_TAG_NAME "Forbidden.rbxm" --clobber

      - name: Push to Roblox
        run: |
          rbxcloud assets update -f "Forbidden.rbxm" -p ${{ vars.ASSET_ID }} -t model-fbx -a ${{ secrets.OPEN_CLOUD_TOKEN }}

  # TODO: add zipped version to assets for non-wally users
